### ISSUE TITLE
Issues on iOS 9.3

### ISSUE THREAD

**Issue by gnazarkin** [html-next/ember-hammertime#14]
Same issue as https://github.com/runspired/ember-hammertime/issues/6. Hammertime not working with iOS 9.3, tested with 4 devices. Works perfectly on 9.2
- Fastlick not installed
- ember-hammertime 1.0.0
- Ember 2.6.2
- Meta tags set to`user-scalable=no, initial-scale=1, maximum-scale=1, minimum-scale=1, width=device-width`
- `touch-action: manipulation` being applied
- Added `[data-ember-action], a, button, input, .link {
  cursor: pointer;
     }` to stylesheet
- Cordova 6.2.0

**Comment by runspired** [comment]
@gnazarkin this is because of your hammertime version.

**Comment by runspired** [comment]
reopening because I'm realizing you said cordova specifically.

are you using the wkWebView engine or the uiWebView engine?

**Comment by gnazarkin** [comment]
uiWebView

**Comment by alizahid** [comment]
This thing never got resolved?

**Comment by runspired** [comment]
@alizahid mostly I never had a chance to get a uiWebView build to test. Theoretically this should not be an issue.... in practice if someone can replicate this consistently in uiWebView on a device and is willing to pair with me it's likely something simple.

**Comment by runspired** [comment]
@alizahid also note, I say theoretically because I was supporting multiple apps running on the mentioned iOS versions with both uiWebView and wkWebView without issue.

**Comment by alizahid** [comment]
@gnazarkin and I have been able to replicate this consistently. I'd like to pair, as you suggested, to get to the bottom of this. FastClick hasn't been updated in over a year and has a bunch of really annoying bugs which make it nearly unusable.

How can I help?

**Comment by runspired** [comment]
@alizahid after I'm done with work today I'll ping you. Same handle for Ember Slack?

**Comment by alizahid** [comment]
@runspired yes.

**Comment by runspired** [comment]
@alizahid @gnazarkin can you check version 1.1 for me (released this evening)? Please make sure to bump your versions of hammer-time in bower.json as well, should also be 1.1

Closing as I believe this is resolved by the release of 1.1.0, will reopen if not.

**Comment by alizahid** [comment]
I'm on iOS 10 now. Still have the delay. @runspired @gnazarkin

**Comment by runspired** [comment]
@arschmitz may be the best person @alizahid

**Comment by alizahid** [comment]
@arschmitz Halp.

**Comment by arschmitz** [comment]
iv never been able to replicate this on iOS 9.3 ill check 10. can you give me any more details on what your doing what elements your seeing delay on exactly how long of a delay are you seeing? Do you see this outside of webviews?

**Comment by alizahid** [comment]
@arschmitz If you have some time, we can talk on Ember Slack and get to the bottom of this. I can show you my code and / or app and answer any questions. We can debug this together.

**Comment by alizahid** [comment]
@arschmitz @gnazarkin I switched to `WKWebView` and that fixes the issue. The Cordova plugin is available here; https://github.com/apache/cordova-plugin-wkwebview-engine

**Comment by alizahid** [comment]
But `WKWebView` has a ton of bugs, too. So this still needs to be resolved on `UIWebView`.

**Comment by diogomafra** [comment]
I think this issue may be fixed by this PR: https://github.com/hammerjs/hammer-time/pull/34

**Comment by alizahid** [comment]
@diogomafra Have you tested?

**Comment by diogomafra** [comment]
@alizahid I've tested it on a page launching from the home screen. I think it has the same behavior on Cordova, but I haven't tested it.

**Comment by rwwagner90** [comment]
@diogomafra @alizahid is this resolved?

**Comment by lukemelia** [comment]
As far as I can tell, this is still an issue.

**Comment by arschmitz** [comment]
hi sorry some how missed this issue way way back but saw this update the original issue on hammer time was closed and working long ago. 

If i could get some fresh reproduction steps or better yet a non working example im happy to look into it though
